const CONFIG = { storeName: "Mega Virtual", whatsapp: "+593987624912" };
const products = [
  {
    id: 1,
    name: "Memoria USB Kingston 8GB",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/8gb.jpg",
    description:
      "Memoria USB Kingston de 8GB, ideal para almacenar y transferir tus archivos de manera rápida y segura.",
    price: "6",
    stock: "1 unidad",
    colors: ["Gris"],
  },
  {
    id: 2,
    name: "Cable HDMI",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/cable5.jpg",
    description:
      "Cable HDMI de alta velocidad, ideal para conectar tus dispositivos y disfrutar de una calidad de imagen y sonido superior.",
    price: "3,50",
    stock: "29 unidades",
    colors: ["Negro", "Rojo"],
  },
  {
    id: 3,
    name: "Audifonos AKG Tipo C",
    category: "Audio",
    image: "assets/images/productos/audio/AUDIFONOSTIPOC.png",
    description:
      "Audífonos AKG Tipo C, diseñados para ofrecer una experiencia de sonido envolvente y de alta calidad.",
    price: "3",
    stock: "3 unidades",
    colors: ["Negro"],
  },
  {
    id: 4,
    name: "Audifonos AKG Jack 3.5mm",
    category: "Audio",
    image: "assets/images/productos/audio/AKGJACK.webp",
    description:
      "Cable de audio jack 3.5mm para audífonos AKG, ideal para conexión con dispositivos compatibles.",
    price: "3",
    stock: "8 unidades",
    colors: ["Negro"],
  },
  {
    id: 5,
    name: "Cable 3 en 1",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/CABLE3EN1.webp",
    description:
      "Este práctico cable 3 en 1 cuenta con diferentes conectores para que puedas cargar distintos dispositivos de forma cómoda y sencilla.",
    price: "3",
    stock: "9 unidades",
    colors: ["Negro"],
  },
  {
    id: 6,
    name: "Cable de carga rapida Tipo c a c 8A",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/cablfast2.webp",
    description:
      "Cable de carga rápida 8A, ideal para cargar dispositivos compatible con tecnología de carga super rápida.",
    price: "2",
    stock: "12 unidades",
    colors: ["Negro"],
  },
  {
    id: 7,
    name: "Cable Tipo c a c",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/cablec.avif",
    description:
      "Cable Tipo C a C, ideal para cargar y transferir datos entre dispositivos compatibles con conectores USB Tipo C.",
    price: "2",
    stock: "12 unidades",
    colors: ["Azul", "Amarillo", "Verde", "Rosado", "Blanco"],
  },
  {
    id: 8,
    name: "Cargador 4 en 1",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/cable4en1.jpg",
    description:
      "Cargador 4 en 1, ideal para cargar múltiples dispositivos al mismo tiempo con diferentes tipos de conectores.",
    price: "3",
    stock: "11 unidades",
    colors: ["Morado", "Gris", "Negro", "Verde"],
  },
  {
    id: 9,
    name: "Adaptador dos en uno Tipo C - modelo 1",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/adaptadoruno.webp",
    description:
      "Adaptador dos en uno Tipo C, ideal para conectar dispositivos con diferentes tipos de puertos y disfrutar de una mayor versatilidad.",
    price: "4",
    stock: "10 unidades",
    colors: ["Negro", "Gris", "Rosa", "Rojo", "Dorado"],
  },
  {
    id: 10,
    name: "Adaptador dos en uno Tipo C - modelo 2",
    category: "Cargadores y adaptadores",
    image: "assets/images/productos/cargadoresyadaptadores/adaptadordos.jpg",
    description:
      "Adaptador dos en uno Tipo C, ideal para conectar dispositivos con diferentes tipos de puertos y disfrutar de una mayor versatilidad.",
    price: "4",
    stock: "12 unidades",
    colors: ["Negro", "Gris", "Rosa", "Rojo", "Dorado"],
  },
  {
    id: 11,
    name: "Combo Teclado y Mouse AOAS A-1019 | Set Completo USB",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/teclado5.webp",
    description:
      "Combo de teclado y mouse AOAS A-1019, ideal para mejorar tu experiencia de trabajo o juego con un set completo y funcional.",
    price: "15",
    stock: "2 unidades",
    colors: ["Gris"],
  },
  {
    id: 12,
    name: "Soportes para laptop",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/soporte1.jpeg",
    description:
      "Soportes para laptop, ideal para mantener tu dispositivo en posición cómoda mientras trabajas.",
    price: "3",
    stock: "11 unidades",
    colors: ["Negro", "Blanco", "Rosa"],
  },
  {
    id: 13,
    name: "Soportes para laptop",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/soporte4.jpg",
    description:
      "Soportes para laptop, ideal para mantener tu dispositivo en posición cómoda mientras trabajas.",
    price: "3",
    stock: "11 unidades",
    colors: ["Negro"],
  },
  {
    id: 14,
    name: "Retrovisor Dash Cam Full HD",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/retrovisor2.jpg",
    description:
      "Retrovisor Dash Cam Full HD, ideal para tener una visión completa de tu entorno mientras conduces.",
    price: "15",
    stock: "3 unidades",
    colors: ["Negro"],
  },
  {
    id: 15,
    name: "Combo Gamer 4 en 1",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/combo1.png",
    description:
      "Combo de accesorios para gamers, ideal para mejorar tu experiencia de juego.",
    price: "25",
    stock: "1 unidad",
    colors: ["Negro"],
  },
  {
    id: 16,
    name: "Fundas Doypacks para coctel",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/doypack.jpg",
    description:
      "Fundas para coctel, ideal para proteger tu bebida mientras disfrutas de tu evento.",
    price: "13,50",
    stock: "50 unidades",
    colors: ["Blanco"],
  },
  {
    id: 17,
    name: "Olla Automática de presión",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/olla2.png",
    description:
      "Olla automática de presión, ideal para cocinar de manera eficiente y rápida.",
    price: "70",
    stock: "1 unidad",
    colors: ["Negro"],
  },
  {
    id: 18,
    name: "Secadora Profesional de cabello SN-1267",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/secadora.jpeg",
    description:
      "Secadora profesional de cabello SN-1267, ideal para secar tu cabello de manera rápida y eficiente.",
    price: "12",
    stock: "1 unidad",
    colors: ["Negro"],
  },
  {
    id: 19,
    name: "Rizador de pelo profesional SN-8558",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/ruilero2.jpeg",
    description:
      "Rizador de pelo profesional SN-8558, ideal para crear ondas y rizos en tu cabello.",
    price: "7",
    stock: "2 unidades",
    colors: ["Rosa"],
  },
  {
    id: 20,
    name: "Plancha de cabello SN-868",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/planchados.jpeg",
    description:
      "Plancha de cabello, ideal para alisar y dar forma a tu cabello.",
    price: "10",
    stock: "1 unidad",
    colors: ["Negro"],
  },
  {
    id: 21,
    name: "Plancha de cabello SN-728",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/plancha2.jpeg",
    description:
      "Plancha de cabello, ideal para alisar y dar forma a tu cabello.",
    price: "12",
    stock: "3 unidades",
    colors: ["Rojo"],
  },
  {
    id: 22,
    name: "Planchilla para el pelo SN-5246",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/rulero.jpeg",
    description:
      "Rulero de cabello, ideal para crear ondas y rizos en tu cabello.",
    price: "12",
    stock: "1 unidad",
    colors: ["Rosa"],
  },
  {
    id: 23,
    name: "Rizador de pelo de tres barriles F-12",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/ruleroi3.jpeg",
    description:
      "Rizador de pelo de tres barriles F-12, ideal para crear ondas y rizos en tu cabello.",
    price: "12",
    stock: "3 unidades",
    colors: ["Rosa"],
  },
  {
    id: 24,
    name: "Mini ventilador de mano",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/VENTILADORTRES.jpg",
    description:
      "Mini ventilador de mano, ideal para mantenerse fresco en días calurosos.",
    price: "4",
    stock: "4 unidades",
    colors: ["Rosa", "Verde", "Naranja", "Amarillo"],
  },
  {
    id: 25,
    name: "Splash Air Body Mist",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/flyer principal.jpg",
    description:
      "Splash Air Body Mist, ideal para mantener tu cuerpo fresco y cómodo.",
    price: "5",
    stock: "24 unidades",
    colors: ["Gris", "Rosa", "Azul", "Verde", "Amarillo"],
  },
  {
    id: 26,
    name: "Rimel para pestañas Sensational Lash",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/rimelUno.jpg",
    description:
      "Rimel para pestañas Sensational Lash, ideal para dar volumen y longitud a tus pestañas.",
    price: "5",
    stock: "1 unidad",
    colors: ["Cafe"],
  },
  {
    id: 27,
    name: "Rimel para pestañas Go Volume Lash",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/rimelDos.jpg",
    description:
      "Rimel para pestañas Go Volume Lash, ideal para dar volumen y longitud a tus pestañas.",
    price: "4",
    stock: "1 unidad",
    colors: ["Amarillo"],
  },
  {
    id: 28,
    name: "Pijama Satine 3 piezas",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/pijamaSatin.jpg",
    description:
      "Pijama Satine para mujer, ideal para un sueño cómodo y relajante.",
    price: "20",
    stock: "10 unidades",
    colors: ["Rosa", "Celeste", "Blanco"],
  },
  {
    id: 29,
    name: "Pijama Camiseta 3 piezas",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/pijamaCamiseta.jpg",
    description:
      "Pijama Camiseta 3 piezas, ideal para un sueño cómodo y relajante.",
    price: "12",
    stock: "11 unidades",
    colors: ["Rosa", "Blanco", "Verde"],
  },
  {
    id: 30,
    name: "Pijama Cereza 3 piezas",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/pijamaCereza.jpg",
    description:
      "Pijama Cereza 3 piezas, ideal para un sueño cómodo y relajante.",
    price: "12",
    stock: "7 unidades",
    colors: ["Rosa", "Blanco", "Verde"],
  },
  {
    id: 31,
    name: "Pijama Ligera 2 piezas",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/pijamaCinco.jpg",
    description:
      "Pijama Ligera 2 piezas, ideal para un sueño cómodo y relajante.",
    price: "5",
    stock: "9 unidades",
    colors: ["Rosa", "Blanco", "Verde"],
  },
  {
    id: 32,
    name: "Adaptador Antena Para Red Wfi Wireless 1200mbps 802.IIN",
    category: "Accesorios",
    image: "assets/images/productos/accesorios/antenawifi.webp",
    description: "Esta Antena Adaptador WiFi USB es la solución ideal para darle Wi-Fi a tu computadora de escritorio (PC) o mejorar la recepción de tu laptop.",
    price: "5",
    stock: "1 unidad",
    colors: ["Negro"],
  },
  {
    id: 33,
    name: "Perfumes Airbody: Tu Aroma Ideal 100 ml",
    category: "Hogar y Belleza",
    image: "assets/images/productos/hogarybelleza/perfume4.jpeg",
    description: "Colección Fragancias Airbody: Tu Aroma Ideal 100 ml (Varios Modelos)" ,
    price: "5",
    stock: "5 unidades",
    colors: ["Negro", "Rosa", "Morado"],
  }
];
